### PR TITLE
Add onLoad and onError callbacks

### PR DESCRIPTION
**Pull request by bildja**
1. I need to show and to do something once image has been loaded and therefore I need a callback for it.
2. I need to send a message to error logger, when image couldn't load.

### CODE REVIEW

**Comment by mbrevda** [comment]
I'm wondering if there is a more general way of approaching this. Could you call the logger from the fallback element?

**Comment by bildja** [comment]
@mbrevda yes, I think I could. Though it still leaves the need of `onLoad` (and this is why I did this PR at the first place), and image API seems to be more consistent with both `onLoad` and `onError`. Besides, I am not sure if sending a log is more of responsibility of the fallback element rather then the whatever component renders the image

**Comment by mbrevda** [comment]
>  I am not sure if sending a log is more of responsibility of the fallback element rather then the whatever component renders the image

Considering [SRP](https://en.wikipedia.org/wiki/Single_responsibility_principle), would it seem true that this lib's responsability is simply loading images/fallbacks? In which case, we can use composition to layer additional responsibilities.

A yet [unreleased prop](https://github.com/mbrevda/react-image/commit/23c28848fbf2938d42e238a8f140f9b833dbdcab#diff-1fdf421c05c1140f6d71444ea2b27638R21) would act as an image wrapper, allowing post processing scenarios such as logging and animations.

To use, create a log element which receivse [these props](https://github.com/mbrevda/react-image/commit/23c28848fbf2938d42e238a8f140f9b833dbdcab#diff-1fdf421c05c1140f6d71444ea2b27638R164). When it loads, if `children` was passed , render them (it's a pre/unloader) and log an error (if the unloader was passed). If the above props were passed, mainly `src`, log that the image was loaded and render it (`return `).

Would that work for your use case?

**Comment by bildja** [comment]
@mbrevda 

Its responsibility will still be simply loading images/fallbacks. The component itself will not start doing logs/any other unrelated start to it. It will just give a consumer of it an ability to do it.
And it looks like with the `container` prop it would be possible to do what I need. Still, I'll suggest you to compare:

```
class MyComponent extends React.Component {
  render() {
    <div>
       <Img src={this.props.imageSrc} onLoad={() => this.setState({showAnotherThing: true})} onError={sendErrorLog} />
        {this.state.showAnotherThing ? <AnotherThing/> : null}
    </div>
  }
}

```

vs

```
class MyComponent extends React.Component {
  render() {
    <div>
       <Img src={this.props.imageSrc} fallbackComponent={WrappedFallbackComponent} container={children => children; /* and I need to find a way to setState for showAnotherThing here for example */}>
        {this.state.showAnotherThing ? <AnotherThing/> : null}
    </div>
  }
}

WrappedFallbackComponent = withErrorLogger(FallbackComponent);
```

**Comment by mbrevda** [comment]
Setup would actually be similar to this:

```js
// image wrapper for images that have loaded succesfully
class ImageOkContainer extends Component {
  componentDidRender(){
     // update logging server that we have show the image
    if (this.props.src) console.log('Image loaded successfully!')
  }

  render() {
    return this.props.children
      ? this.props.children()
      : <img {...this.props} />
  }
}
```

```js
// unloader, used as a fallback if all images fail to load
class Unloader extends Component {
  componentDidRender(){
    // log failed to load error
    console.error('Image failed to load!')
  }

  render() {
    return <span>Image failed to load!</span>
  }
}
```

```js

// demo component
<Img
  src={this.props.imageSrc}
  loader={<span>Loading...</span>}
  unloader={Unloader}
  container={ImageContainer}
/>

```

**Comment by bildja** [comment]
@mbrevda this is pretty much what I showed. So first, comparing the two approaches, the one with callbacks is very concise and very react-way and second is verbose and also kind of react way, but in a bit different way and I'd stick with the callbacks.
And, second, example with `ImageOkContainer` does not actually solve the case where I need to `setState` on the component that renders `<Img`, only thing, so I would need to pass this callback to the `container` property anyway and it'd be really awkward

**Comment by bildja** [comment]
@mbrevda yes, that's what I meant by "I would need to pass this callback to the container property anyway". So, you see the difference between the example you give me and an example with callbacks?
Regarding your question "what `showAnotherThing` is in your example":
For example, currently I have a feature where I render two things:
1. Rectangles around faces on top of the image. While I can agree it logically can belong inside the `` component as a child, I have reasons to put it in a different level.
2. A toggle element which turns on/off the faces on top of images and it belongs very different level on the component tree, so I need to only show it by a state flag, when the image is loaded.

If I used just `` element what I would do is exactly passing `onload={}` and `onerrror={}` properties and setting the state value accordingly

**Comment by mbrevda** [comment]
> So, you see the difference between the example you give me and an example with callbacks?

Perhaps I'm not following, but I'm not convinced that anything needs to be added here. Regardless of the method, you'll need to use callbacks to hoist the state up to the parent.

**Comment by dum3ng** [comment]
I would also like to the callback way. 
It does not add more functionality to this component but just provide a interface for users to do other things.
The way with a container is not a clear way, at least to me.

**Comment by mbrevda** [comment]
It is now possible to inject a custom image loader with any desired behavior. You can pass it as a prop to the `useImage` hook or to the component, see more [here](https://github.com/mbrevda/react-image#useimage-api).

**Comment by mbrevda** [comment]
It is now possible to inject a custom image loader with any desired behavior. You can pass it as a prop to the `useImage` hook or to the component, see more [here](https://github.com/mbrevda/react-image#useimage-api).

**Pull request closed without merging**
